namespace Scry.SourceGenerator;

/// <summary>
/// Reads the server model assembly (pointed at by the <c>ScryModelDll</c> build property) and
/// generates strongly-typed client query DTOs, re-emitted enums, and a query entry point. The
/// assembly is read as metadata only — never referenced, loaded, or executed.
/// </summary>
[Generator]
public class ScryGenerator :
    IIncrementalGenerator
{
    const string generatedNamespace = "Scry.Generated";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var path = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) => GetProperty(provider, "build_property.ScryModelDll"));

        // The DLL is read out of band, so Roslyn cannot see content changes from the path alone.
        // A stamp property (a content hash set by the build targets) folds content into the pipeline
        // input so the model is re-read exactly when it changes.
        var stamp = context.AnalyzerConfigOptionsProvider
            .Select((provider, _) => GetProperty(provider, "build_property.ScryModelStamp"));

        var model = path
            .Combine(stamp)
            .Select((pair, _) => MetadataModelReader.Read(pair.Left));

        context.RegisterSourceOutput(model, Emit);
    }

    static string? GetProperty(AnalyzerConfigOptionsProvider provider, string key)
    {
        if (provider.GlobalOptions.TryGetValue(key, out var value) &&
            !string.IsNullOrWhiteSpace(value))
        {
            return value;
        }

        return null;
    }

    static readonly DiagnosticDescriptor readFailed = new(
        "SCRY001",
        "Failed to read the Scry model assembly",
        "{0}",
        "Scry",
        DiagnosticSeverity.Error,
        true);

    static void Emit(SourceProductionContext context, ModelExtract extract)
    {
        if (extract.Error is { } error)
        {
            context.ReportDiagnostic(Diagnostic.Create(readFailed, Location.None, error));
            return;
        }

        if (extract.Sources.Length == 0)
        {
            return;
        }

        foreach (var source in extract.Sources)
        {
            context.AddSource($"{source.ModelName}.g.cs", EmitModel(source));
        }

        if (extract.Enums.Length > 0)
        {
            context.AddSource("ScryEnums.g.cs", EmitEnums(extract.Enums));
        }

        context.AddSource("ScryQuery.g.cs", EmitQuery(extract.Sources));
    }

    static string EmitModel(SourceInfo source)
    {
        var builder = Header();
        builder.AppendLine($"/// <summary>Client query model for the '{source.SourceName}' {source.Kind.ToString().ToLowerInvariant()} source.</summary>");
        builder.AppendLine($"public sealed class {source.ModelName}");
        builder.AppendLine("{");
        foreach (var property in source.Properties)
        {
            var initializer = property.NeedsNullDefault ? " = null!;" : "";
            builder.AppendLine($"    public {property.TypeDisplay} {property.Name} {{ get; init; }}{initializer}");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    static string EmitEnums(EquatableArray<EnumInfo> enums)
    {
        var builder = Header();
        foreach (var enumeration in enums)
        {
            builder.AppendLine($"public enum {enumeration.Name}");
            builder.AppendLine("{");
            foreach (var member in enumeration.Members)
            {
                builder.AppendLine($"    {member},");
            }

            builder.AppendLine("}");
            builder.AppendLine();
        }

        return builder.ToString();
    }

    static string EmitQuery(EquatableArray<SourceInfo> sources)
    {
        var builder = Header();
        builder.AppendLine("/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>");
        builder.AppendLine("public sealed class ScryQuery");
        builder.AppendLine("{");
        builder.AppendLine("    readonly global::Scry.Client.ScryClient client;");
        builder.AppendLine();
        builder.AppendLine("    public ScryQuery(global::Scry.Client.ScryClient client) => this.client = client;");
        foreach (var source in sources)
        {
            builder.AppendLine();
            builder.AppendLine(
                $"    public global::System.Linq.IQueryable<{source.ModelName}> {source.SourceName} =>");
            builder.AppendLine(
                $"        client.Source<{source.ModelName}>(\"{source.SourceName}\");");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    static StringBuilder Header()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine($"namespace {generatedNamespace};");
        builder.AppendLine();
        return builder;
    }
}
