global using System.Buffers;
global using System.Collections;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.Linq.Expressions;
global using System.Net.Http.Headers;
global using System.Text.Json;
global using Microsoft.Extensions.DependencyInjection;
global using Scry;
