//HintName: HolidayQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Pneumatic.Generated;

/// <summary>Client query model for the 'Holiday' poco source.</summary>
public sealed class HolidayQueryModel
{
    public string Name { get; init; } = null!;
    public global::System.DateOnly Date { get; init; }
}
