//HintName: PneumaticQuery.g.cs
// <auto-generated/>
#nullable enable
namespace Pneumatic.Generated;

/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>
public sealed class PneumaticQuery
{
    readonly global::Pneumatic.Client.PneumaticClient client;

    public PneumaticQuery(global::Pneumatic.Client.PneumaticClient client) => this.client = client;

    public global::System.Linq.IQueryable<EmployeeQueryModel> Employee =>
        client.Source<EmployeeQueryModel>("Employee");

    public global::System.Linq.IQueryable<EmployeeSummaryQueryModel> EmployeeSummary =>
        client.Source<EmployeeSummaryQueryModel>("EmployeeSummary");

    public global::System.Linq.IQueryable<HolidayQueryModel> Holiday =>
        client.Source<HolidayQueryModel>("Holiday");
}
