global using System.Net;
global using System.Text;
global using System.Text.Json;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.TestHost;
global using Microsoft.Extensions.DependencyInjection;
global using Scry;
global using Scry.Generated;
global using TUnit.Assertions.Enums;
