<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <ProjectReference Include="..\src\Pneumatic.Server\Pneumatic.Server.csproj" />
    <ProjectReference Include="..\src\Pneumatic.Client\Pneumatic.Client.csproj" />
    <ProjectReference Include="..\samples\Sample.Model\Sample.Model.csproj" />
  </ItemGroup>
</Project>
