<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.NUnit" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="NaughtyStrings" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <ProjectReference Include="..\Pneumatic.Wire\Pneumatic.Wire.csproj" />
    <ProjectReference Include="..\Pneumatic.Annotations\Pneumatic.Annotations.csproj" />
    <ProjectReference Include="..\Pneumatic.Server\Pneumatic.Server.csproj" />
    <ProjectReference Include="..\Pneumatic.Client\Pneumatic.Client.csproj" />
  </ItemGroup>
</Project>
