//HintName: HolidayQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Holiday' poco source.</summary>
[global::Scry.Client.ScryModel("Holiday", "Name", "Date")]
public class HolidayQueryModel
{
    public string Name { get; init; } = null!;
    public global::System.DateOnly Date { get; init; }
}
