//HintName: OrderLineQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'OrderLine' entity source.</summary>
[global::Scry.ScryModel("OrderLine", "Id", "Price")]
public class OrderLineQueryModel
{
    public int Id { get; init; }
    public decimal Price { get; init; }
}
