//HintName: EmployeeSummaryQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Headcount' view source.</summary>
[global::Scry.ScryModel("Headcount", "Total")]
public class EmployeeSummaryQueryModel
{
    public int Total { get; init; }
}
