//HintName: EmployeeSummaryQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'EmployeeSummary' view source.</summary>
[global::Scry.Client.ScryModel("EmployeeSummary", "Department", "Headcount")]
public class EmployeeSummaryQueryModel
{
    public string Department { get; init; } = null!;
    public int Headcount { get; init; }
}
