//HintName: OrderQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Order' entity source.</summary>
[global::Scry.ScryModel("Order", "Id", "Region")]
public class OrderQueryModel
{
    public int Id { get; init; }
    public string Region { get; init; } = null!;
    public global::System.Collections.Generic.IReadOnlyList<OrderLineQueryModel> Lines { get; init; } = null!;
}
