//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
[global::Scry.ScryModel("Employee", "Id", "event", "class")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    public string @event { get; init; } = null!;
    public Kind @class { get; init; }
}
