//HintName: OrderQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Order' entity source.</summary>
public sealed class OrderQueryModel
{
    public int Id { get; init; }
    public string Region { get; init; } = null!;
    public global::System.Collections.Generic.IReadOnlyList<OrderLineQueryModel> Lines { get; init; } = null!;
}
