//HintName: PayrollQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Payroll' complex type.</summary>
[global::Scry.ScrySensitive]
public class PayrollQueryModel
{
    public decimal Salary { get; init; }
}
