//HintName: DepartmentQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Department' entity source.</summary>
[global::Scry.ScryModel("Department", "Id", "Name")]
public class DepartmentQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
}
