//HintName: VehicleQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Vehicle' entity source.</summary>
[global::Scry.ScryModel("Vehicle", "Id", "Name", "Stamp", "Wheels")]
public class VehicleQueryModel : AssetQueryModel
{
    public long Stamp { get; init; }
    public int Wheels { get; init; }
}
