//HintName: InvoiceQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Invoice' entity source.</summary>
[global::Scry.ScryModel("Invoice", "CreatedBy", "Id", "Number", "Notes")]
public class InvoiceQueryModel
{
    public string CreatedBy { get; init; } = null!;
    public int Id { get; init; }
    public string Number { get; init; } = null!;
    public string Notes { get; init; } = null!;
    public global::System.Collections.Generic.IReadOnlyList<string> Tags { get; init; } = null!;
    public global::System.Collections.Generic.IReadOnlyList<int> Weights { get; init; } = null!;
}
