//HintName: ScryQuery.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>
public sealed class ScryQuery
{
    /// <summary>
    /// A hash of the queryable surface this client was generated against. Attached to each
    /// request so the server can identify a client generated against a different model.
    /// </summary>
    public const string SchemaStamp = "7f00ba6dd171ecb1b77c0d396566c4ecfea445648491fe45d919f5bea91f6330";

    readonly global::Scry.Client.ScryClient client;

    public ScryQuery(global::Scry.Client.ScryClient client)
    {
        this.client = client;
        client.SchemaStamp = SchemaStamp;
    }

    public global::System.Linq.IQueryable<EmployeeQueryModel> Employee =>
        client.Source<EmployeeQueryModel>("Employee", ["Id", "Name"]);
}
