//HintName: ScryEnums.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

public enum Status
{
    FullTime = 0,
    PartTime = 1,
    Contractor = 2,
}

