//HintName: CustomerQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Customer' entity source.</summary>
[global::Scry.ScryModel("Customer", "Id", "Notes", "Name")]
public class CustomerQueryModel
{
    public global::System.Guid? Id { get; init; }
    public string Notes { get; init; } = null!;
    public string Name { get; init; } = null!;
}
