//HintName: DepartmentQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Department' entity source.</summary>
[global::System.ObsoleteAttribute("Flattened into Employee.Name.")]
[global::Scry.ScryModel("Department", "Id")]
public class DepartmentQueryModel
{
    public int Id { get; init; }
}
