//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Staff' entity source.</summary>
public sealed class EmployeeQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
}
