//HintName: ScryQuery.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>
public sealed class ScryQuery
{
    /// <summary>
    /// A hash of the queryable surface this client was generated against. Attached to each
    /// request so the server can identify a client generated against a different model.
    /// </summary>
    public const string SchemaStamp = "CWGq-OX_3lJgq0WU";

    readonly global::Scry.Client.ScryClient client;

    public ScryQuery(global::Scry.Client.ScryClient client)
    {
        this.client = client;
        client.SchemaStamp = SchemaStamp;
    }

    public global::System.Linq.IQueryable<AssetQueryModel> Asset =>
        client.Source<AssetQueryModel>("Asset", ["Id", "Name"]);

    public global::System.Linq.IQueryable<VehicleQueryModel> Vehicle =>
        client.Source<VehicleQueryModel>("Vehicle", ["Id", "Name", "Wheels"]);
}
