//HintName: ScryCommands.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>The 'Reschedule' command, sent through <c>ScryCommands</c>.</summary>
[global::Scry.ScryCommand("Reschedule", Target = "Sitting", Keys = new[] {"Id"})]
public sealed class Reschedule
{
    public int Id { get; init; }
    public global::System.DayOfWeek Day { get; init; }
    public global::System.Collections.Generic.IReadOnlyList<global::System.DateTimeKind?> Clocks { get; init; } = null!;
}

/// <summary>The commands this client may send, each answered with its outcome.</summary>
public sealed class ScryCommands
{
    global::Scry.ScryClient client;

    public ScryCommands(global::Scry.ScryClient client) =>
        this.client = client;

    /// <summary>Sends 'Reschedule', answering with its outcome.</summary>
    public global::System.Threading.Tasks.Task<global::Scry.ScryCommandOutcome> Reschedule(
        global::Scry.Generated.Reschedule command,
        global::System.Threading.CancellationToken cancel = default) =>
        client.SendCommandAsync(command, cancel);

    /// <summary>
    /// Whether this caller may send 'Reschedule' at all, as the server last said. Advisory:
    /// the server decides again on every command. False until the server has answered.
    /// </summary>
    public bool CanReschedule => client.Can("Reschedule");
}
