//HintName: ScryEnums.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

[global::System.Flags]
public enum Perks : byte
{
    None = 0,
    Parking = 1,
    Gym = 2,
    Remote = 4,
}

public enum Priority
{
    Low = 10,
    High = 20,
}

