//HintName: OrderQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Order' entity source.</summary>
[global::Scry.ScryModel("Order", "Amount")]
public class OrderQueryModel
{
    public decimal Amount { get; init; }
}
