//HintName: RetiredQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Retired' entity source.</summary>
[global::System.ObsoleteAttribute("Superseded by Employee.Active.")]
[global::Scry.ScryModel("Retired", "Id")]
public class RetiredQueryModel
{
    public int Id { get; init; }
}
