//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
[global::Scry.ScryModel("Employee", "Id", "Perks", "Priority")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    public Perks Perks { get; init; }
    public Priority? Priority { get; init; }
}
