//HintName: DocumentQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Document' entity source.</summary>
[global::Scry.ScryModel("Document", "Id", "Title", "CanRename")]
public class DocumentQueryModel
{
    public int Id { get; init; }
    public string Title { get; init; } = null!;
    /// <summary>Whether this caller may send 'Rename' against this row, as the server's policy for it decides.</summary>
    public bool CanRename { get; init; }
}
