//HintName: ScryQuery.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>
public sealed class ScryQuery
{
    /// <summary>
    /// A hash of the queryable surface this client was generated against. Attached to each
    /// request so the server can identify a client generated against a different model.
    /// </summary>
    public const string SchemaStamp = "yBqMAsrOsp3FNrXj";

    readonly global::Scry.ScryClient client;

    public ScryQuery(global::Scry.ScryClient client)
    {
        this.client = client;
        client.SchemaStamp = SchemaStamp;
    }

    public global::System.Linq.IQueryable<EmployeeQueryModel> Employee =>
        client.Source<EmployeeQueryModel>("Employee", ["Id", "Code", "Name", "Active"]);

    [global::System.ObsoleteAttribute("Flattened into Employee.Name.")]
    public global::System.Linq.IQueryable<DepartmentQueryModel> Department =>
        client.Source<DepartmentQueryModel>("Department", ["Id"]);

    [global::System.ObsoleteAttribute("Superseded by Employee.Active.")]
    public global::System.Linq.IQueryable<RetiredQueryModel> Retired =>
        client.Source<RetiredQueryModel>("Retired", ["Id"]);
}
