//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
public sealed class EmployeeQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
    public Status Status { get; init; }
    public bool Active { get; init; }
    public int? ManagerId { get; init; }
    public EmployeeQueryModel? Manager { get; init; }
    public byte[] Avatar { get; init; } = null!;
}
