//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
[global::Scry.ScryModel("Employee", "Id", "Name")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
    public AddressQueryModel? Address { get; init; }
    public AddressQueryModel? SecondaryAddress { get; init; }
    public global::System.Collections.Generic.IReadOnlyList<AddressQueryModel> PreviousAddresses { get; init; } = null!;
}
