//HintName: ScryQuery.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>
public sealed class ScryQuery
{
    /// <summary>
    /// A hash of the queryable surface this client was generated against. Attached to each
    /// request so the server can identify a client generated against a different model.
    /// </summary>
    public const string SchemaStamp = "wD-O0DfMZ_zvEg8p";

    readonly global::Scry.ScryClient client;

    public ScryQuery(global::Scry.ScryClient client)
    {
        this.client = client;
        client.SchemaStamp = SchemaStamp;
    }

    public global::System.Linq.IQueryable<EmployeeQueryModel> Staff =>
        client.Source<EmployeeQueryModel>("Staff", ["Id", "Name"]);

    public global::System.Linq.IQueryable<EmployeeSummaryQueryModel> Headcount =>
        client.Source<EmployeeSummaryQueryModel>("Headcount", ["Total"]);

    public global::System.Linq.IQueryable<HolidayQueryModel> PublicHoliday =>
        client.Source<HolidayQueryModel>("PublicHoliday", ["Name"]);

    public global::System.Linq.IQueryable<OrderQueryModel> Order =>
        client.Source<OrderQueryModel>("Order", ["Amount"]);
}
