//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
[global::Scry.ScryModel("Employee", "Id", "Name", "Status", "Active", "CanDeleteEmployee", "CanRenameEmployee")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
    public Status Status { get; init; }
    public bool Active { get; init; }
    public DepartmentQueryModel? Department { get; init; }
    /// <summary>Whether this caller may send 'DeleteEmployee' against this row, as the server's policy for it decides.</summary>
    public bool CanDeleteEmployee { get; init; }
    /// <summary>Whether this caller may send 'RenameEmployee' against this row, as the server's policy for it decides.</summary>
    public bool CanRenameEmployee { get; init; }
}
