//HintName: ScryCommands.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>The 'CreateEmployee' command, sent through <c>ScryCommands</c>.</summary>
[global::System.ObsoleteAttribute("Hire through the portal.")]
[global::Scry.ScryCommand("CreateEmployee", Result = typeof(global::Scry.Generated.EmployeeCreated))]
public sealed class CreateEmployee
{
    public string Name { get; init; } = null!;
    public int DepartmentId { get; init; }
    public Status Status { get; init; }
    public global::System.Collections.Generic.IReadOnlyList<string> Tags { get; init; } = null!;
    public global::System.DateOnly? Starts { get; init; }
}

/// <summary>The 'DeleteEmployee' command, sent through <c>ScryCommands</c>.</summary>
[global::Scry.ScryCommand("DeleteEmployee", Target = "Employee", Keys = new[] {"Id"})]
public sealed class DeleteEmployee
{
    public int Id { get; init; }
}

/// <summary>The 'RenameEmployee' command, sent through <c>ScryCommands</c>.</summary>
[global::Scry.ScryCommand("RenameEmployee", Target = "Employee", Keys = new[] {"Id"})]
public sealed class RenameEmployee
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
}

/// <summary>What a command answers with: 'EmployeeCreated'.</summary>
public sealed class EmployeeCreated
{
    public int Id { get; init; }
}

/// <summary>The commands this client may send, each answered with its outcome.</summary>
public sealed class ScryCommands
{
    global::Scry.ScryClient client;

    public ScryCommands(global::Scry.ScryClient client) =>
        this.client = client;

    /// <summary>Sends 'CreateEmployee', answering with its outcome.</summary>
    [global::System.ObsoleteAttribute("Hire through the portal.")]
    public global::System.Threading.Tasks.Task<global::Scry.ScryCommandOutcome<global::Scry.Generated.EmployeeCreated>> CreateEmployee(
        global::Scry.Generated.CreateEmployee command,
        global::System.Threading.CancellationToken cancel = default) =>
        client.SendCommandAsync<global::Scry.Generated.CreateEmployee, global::Scry.Generated.EmployeeCreated>(command, cancel);

    /// <summary>
    /// Whether this caller may send 'CreateEmployee' at all, as the server last said. Advisory:
    /// the server decides again on every command. False until the server has answered.
    /// </summary>
    public bool CanCreateEmployee => client.Can("CreateEmployee");

    /// <summary>Sends 'DeleteEmployee', answering with its outcome.</summary>
    public global::System.Threading.Tasks.Task<global::Scry.ScryCommandOutcome> DeleteEmployee(
        global::Scry.Generated.DeleteEmployee command,
        global::System.Threading.CancellationToken cancel = default) =>
        client.SendCommandAsync(command, cancel);

    /// <summary>
    /// Whether this caller may send 'DeleteEmployee' at all, as the server last said. Advisory:
    /// the server decides again on every command. False until the server has answered.
    /// </summary>
    public bool CanDeleteEmployee => client.Can("DeleteEmployee");

    /// <summary>Sends 'RenameEmployee', answering with its outcome.</summary>
    public global::System.Threading.Tasks.Task<global::Scry.ScryCommandOutcome> RenameEmployee(
        global::Scry.Generated.RenameEmployee command,
        global::System.Threading.CancellationToken cancel = default) =>
        client.SendCommandAsync(command, cancel);

    /// <summary>
    /// Whether this caller may send 'RenameEmployee' at all, as the server last said. Advisory:
    /// the server decides again on every command. False until the server has answered.
    /// </summary>
    public bool CanRenameEmployee => client.Can("RenameEmployee");
}
