//HintName: HolidayQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'PublicHoliday' poco source.</summary>
public sealed class HolidayQueryModel
{
    public string Name { get; init; } = null!;
}
