//HintName: HolidayQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'PublicHoliday' poco source.</summary>
[global::Scry.ScryModel("PublicHoliday", "Name")]
public class HolidayQueryModel
{
    public string Name { get; init; } = null!;
}
