//HintName: OrderQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Order' entity source.</summary>
[global::Scry.Client.ScryModel("Order", "Amount")]
public class OrderQueryModel
{
    public decimal Amount { get; init; }
}
