//HintName: ScryCommands.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>The 'Rename' command, sent through <c>ScryCommands</c>.</summary>
[global::Scry.ScryCommand("Rename", Target = "Document", Keys = new[] {"Id"}, Result = typeof(global::Scry.Generated.Renamed))]
public sealed class Rename
{
    public int Id { get; init; }
    public string Title { get; init; } = null!;
}

/// <summary>What a command answers with: 'Renamed'.</summary>
public sealed class Renamed
{
    public int Id { get; init; }
    public string Title { get; init; } = null!;
}

/// <summary>The commands this client may send, each answered with its outcome.</summary>
public sealed class ScryCommands
{
    global::Scry.ScryClient client;

    public ScryCommands(global::Scry.ScryClient client) =>
        this.client = client;

    /// <summary>Sends 'Rename', answering with its outcome.</summary>
    public global::System.Threading.Tasks.Task<global::Scry.ScryCommandOutcome<global::Scry.Generated.Renamed>> Rename(
        global::Scry.Generated.Rename command,
        global::System.Threading.CancellationToken cancel = default) =>
        client.SendCommandAsync<global::Scry.Generated.Rename, global::Scry.Generated.Renamed>(command, cancel);

    /// <summary>
    /// Whether this caller may send 'Rename' at all, as the server last said. Advisory:
    /// the server decides again on every command. False until the server has answered.
    /// </summary>
    public bool CanRename => client.Can("Rename");
}
