//HintName: InvoiceQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Invoice' entity source.</summary>
[global::Scry.ScryModel("Invoice", "Id", "Stage", "ParentId", "Number", "Notes")]
public class InvoiceQueryModel
{
    public int Id { get; init; }
    public Stage Stage { get; init; }
    public int? ParentId { get; init; }
    public global::System.Collections.Generic.IReadOnlyList<int> Related { get; init; } = null!;
    public global::System.Collections.Generic.IReadOnlyList<Stage> History { get; init; } = null!;
    public string Number { get; init; } = null!;
    public string Notes { get; init; } = null!;
    public CustomerQueryModel? Customer { get; init; }
}
