//HintName: HolidayQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'PublicHoliday' poco source.</summary>
[global::Scry.Client.ScryModel("PublicHoliday", "Name")]
public class HolidayQueryModel
{
    public string Name { get; init; } = null!;
}
