//HintName: AddressQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Address' complex type.</summary>
public class AddressQueryModel
{
    public string City { get; init; } = null!;
    public string Country { get; init; } = null!;
}
