//HintName: ScryQuery.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Entry point for writing LINQ queries against the allow-listed sources.</summary>
public sealed class ScryQuery
{
    readonly global::Scry.Client.ScryClient client;

    public ScryQuery(global::Scry.Client.ScryClient client) => this.client = client;

    public global::System.Linq.IQueryable<EmployeeQueryModel> Employee =>
        client.Source<EmployeeQueryModel>("Employee");
}
