//HintName: OrderLineQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'OrderLine' entity source.</summary>
public sealed class OrderLineQueryModel
{
    public int Id { get; init; }
    public decimal Price { get; init; }
}
