//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
[global::Scry.Client.ScryModel("Employee", "Id", "Name")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
    public AddressQueryModel? Address { get; init; }
    public AddressQueryModel? SecondaryAddress { get; init; }
}
