//HintName: TagsQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Tags' entity source.</summary>
[global::Scry.ScryModel("Tags", "Id")]
public class TagsQueryModel
{
    public int Id { get; init; }
}
