//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Staff' entity source.</summary>
[global::Scry.ScryModel("Staff", "Id", "Name")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
}
