//HintName: EmployeeQueryModel.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0612, CS0618
namespace Scry.Generated;

/// <summary>Client query model for the 'Employee' entity source.</summary>
[global::Scry.ScryModel("Employee", "Id", "Code", "Name", "Active")]
public class EmployeeQueryModel
{
    public int Id { get; init; }
    [global::System.ObsoleteAttribute("Use Name instead: \"FullName\" was split in the C:\\Payroll migration.")]
    public string Code { get; init; } = null!;
    public string Name { get; init; } = null!;
    [global::System.ObsoleteAttribute]
    public bool Active { get; init; }
    public DepartmentQueryModel? Department { get; init; }
}
