//HintName: AssetQueryModel.g.cs
// <auto-generated/>
#nullable enable
namespace Scry.Generated;

/// <summary>Client query model for the 'Asset' entity source.</summary>
[global::Scry.ScryModel("Asset", "Id", "Name")]
public class AssetQueryModel
{
    public int Id { get; init; }
    public string Name { get; init; } = null!;
}
