global using System.Buffers;
global using System.Diagnostics.Metrics;
global using System.Globalization;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.Json.Serialization.Metadata;
global using System.Text.RegularExpressions;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
global using NUnit.Framework;
global using Scry;
global using VerifyTests.DiffPlex;
global using static VerifyNUnit.Verifier;
global using System.Buffers.Text;
global using System.Reflection.Emit;
global using Microsoft.AspNetCore.Http;