global using System.Buffers;
global using System.Globalization;
global using System.Reflection;
global using System.Text;
global using System.Text.Json;
global using Basic.Reference.Assemblies;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Completion;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.Host.Mef;
global using Microsoft.CodeAnalysis.Text;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Scry;
global using Cancel = System.Threading.CancellationToken;
global using CancelSource = System.Threading.CancellationTokenSource;
