<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Verify.NUnit" />
    <PackageReference Include="Verify.DiffPlex" />
    <PackageReference Include="Verify.SourceGenerators" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <ProjectReference Include="..\Skry.SourceGenerator\Skry.SourceGenerator.csproj" />
    <ProjectReference Include="..\Skry.Annotations\Skry.Annotations.csproj" />
  </ItemGroup>
</Project>
